INSERT INTO PUBLIC.FORMULAIRE_VALUE (ID, CODE_VALUE, LIBELLE_VALUE, FORMULAIREPARAMETER_CODE) VALUES (1, 'SAS_BASE', 'SAS_BASE', 'PRODUIT');
INSERT INTO PUBLIC.FORMULAIRE_VALUE (ID, CODE_VALUE, LIBELLE_VALUE, FORMULAIREPARAMETER_CODE) VALUES (2, 'SAEG', 'SASEG', 'PRODUIT');
INSERT INTO PUBLIC.FORMULAIRE_VALUE (ID, CODE_VALUE, LIBELLE_VALUE, FORMULAIREPARAMETER_CODE) VALUES (4, 'OUI', 'OUI', 'SASETS');
INSERT INTO PUBLIC.FORMULAIRE_VALUE (ID, CODE_VALUE, LIBELLE_VALUE, FORMULAIREPARAMETER_CODE) VALUES (5, 'NON', 'NON', 'SASETS');