INSERT INTO PUBLIC.CONTACTS (ID, NAME, CONTACT_EMAIL, TEAM_ID) VALUES (0, 'dssdqf', 'sdfsqdf', 449);
INSERT INTO PUBLIC.CONTACTS (ID, NAME, CONTACT_EMAIL, TEAM_ID) VALUES (1, 'sqfdsf', 'qsdfsqdfqs', 1);
INSERT INTO PUBLIC.CONTACTS (ID, NAME, CONTACT_EMAIL, TEAM_ID) VALUES (705, 'dsfqdf', 'sdfsd', 1);
INSERT INTO PUBLIC.CONTACTS (ID, NAME, CONTACT_EMAIL, TEAM_ID) VALUES (737, 'sqdf', 'sqdfqsf', 3);