INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (1, 'RISK', 'PILOTAGE');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (2, 'SALES', 'RISQUE');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (34, 'MARKETING', 'DIVERS');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (66, 'ACCOUNTING', 'LEGALITY');