INSERT INTO PUBLIC.PRODUCT (ID, ADMIN, NAME) VALUES (1, false, 'SAS BASE');
INSERT INTO PUBLIC.PRODUCT (ID, ADMIN, NAME) VALUES (2, false, 'SAS EG');
INSERT INTO PUBLIC.PRODUCT (ID, ADMIN, NAME) VALUES (3, false, 'SAS addin');
INSERT INTO PUBLIC.PRODUCT (ID, ADMIN, NAME) VALUES (4, false, 'SAS Web');