INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 1', 1, 1, 'JAMES SMITH', 'james.smith@gmail.com');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 2', 2, 1, 'ELTON JOHN', 'elton.john@gmail.com');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 3', 3, 2, 'STEVE KEAN', 'steave.kean@gmail.com');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 4', 449, 1, 'ALBERT KHAN', 'albert.khan@gmail.com');